/**
 * Base de dados de Personagens Bíblicos.
 * Busca por nome, livro, período ou papel na narrativa.
 */

export interface PersonagemBiblico {
  id: string;
  nome: string;
  nomesAlternativos?: string[];
  livro?: string;
  testamento: 'AT' | 'NT';
  periodo?: string;           // ex: "Monarquia", "Exílio", "Nova Aliança"
  dataAproximada?: string;    // ex: "c. 1800 a.C."
  papel: string;              // ex: "Profeta", "Rei", "Apóstolo"
  categoria: string;          // ex: "Profetas Maiores", "Evangelhos"
  resumo: string;
  caracteristicas: string[];
  principaisAcontecimentos: string[];
  passagensRelevantes: string[];
  relacionados?: string[];    // nomes de personagens relacionados
}

export const PERSONAGENS: PersonagemBiblico[] = [
  // ─── PATRIARCAS ──────────────────────────────────────────────────────────────
  {
    id: 'adão',
    nome: 'Adão',
    testamento: 'AT',
    periodo: 'Criação',
    dataAproximada: 'c. 4000 a.C.',
    papel: 'Primeiro ser humano',
    categoria: 'Pentateuco',
    livro: 'Gênesis',
    resumo: 'Primeiro homem criado por Deus, colocado no Jardim do Éden. Sua desobediência trouxe o pecado ao mundo (Romanos 5:12).',
    caracteristicas: ['Criado à imagem de Deus', 'Primeiro sacerdote', 'Agricultor'],
    principaisAcontecimentos: ['Criação no Éden', 'Nomeação dos animais', 'Queda pelo pecado', 'Expulsão do Éden', 'Nascimento de Caim, Abel e Sete'],
    passagensRelevantes: ['Gênesis 1-5', 'Romanos 5:12-21', '1 Coríntios 15:22'],
    relacionados: ['Eva', 'Caim', 'Abel', 'Sete', 'Noé'],
  },
  {
    id: 'eva',
    nome: 'Eva',
    testamento: 'AT',
    periodo: 'Criação',
    dataAproximada: 'c. 4000 a.C.',
    papel: 'Primeira mulher',
    categoria: 'Pentateuco',
    livro: 'Gênesis',
    resumo: 'Primeira mulher, criada da costela de Adão. Seduzida pela serpente, comeu do fruto proibido e envolveu Adão na queda.',
    caracteristicas: ['Mãe da humanidade', 'Primeira a pecar', 'Feita da costela de Adão'],
    principaisAcontecimentos: ['Criação', 'Sedução pela serpente', 'Queda', 'Parto de Caim, Abel e Sete'],
    passagensRelevantes: ['Gênesis 2-4', '2 Coríntios 11:3', '1 Timóteo 2:13-14'],
    relacionados: ['Adão', 'Caim', 'Abel', 'Serpente'],
  },
  {
    id: 'abraham',
    nome: 'Abraão',
    nomesAlternativos: ['Abrão', 'Abraham'],
    testamento: 'AT',
    periodo: 'Patriarcas',
    dataAproximada: 'c. 2000 a.C.',
    papel: 'Pai da fé / Patriarca',
    categoria: 'Pentateuco',
    livro: 'Gênesis',
    resumo: 'Chamado por Deus para deixar sua terra e ir para Canaã. Pai de Isaque e antencipador da fé cristã (Hebreus 11).',
    caracteristicas: ['Pai da fé', 'Amigo de Deus', 'Hospitaleiro', 'Obediente até ao sacrifício'],
    principaisAcontecimentos: ['Chamado de Deus (Ur)', 'Pacto em Génesis 15', 'Sacrifício de Isaque (Moriá)', 'Destruição de Sodoma', 'Nascimento de Isaque'],
    passagensRelevantes: ['Gênesis 12-25', 'Romanos 4', 'Hebreus 11:8-19', 'Tiago 2:21-23'],
    relacionados: ['Sara', 'Isaque', 'Ismael', 'Ló', 'Melquisedeque'],
  },
  {
    id: 'isaque',
    nome: 'Isaque',
    testamento: 'AT',
    periodo: 'Patriarcas',
    dataAproximada: 'c. 1900 a.C.',
    papel: 'Patriarca',
    categoria: 'Pentateuco',
    livro: 'Gênesis',
    resumo: 'Filho de Abraão e Sara, nascido miraculosamente. Pai de Jacó e Esaú. Figura de Cristo como sacrifício.',
    caracteristicas: ['Nascido miraculosamente', 'Pacífico', 'Símbolo de provisão divina'],
    principaisAcontecimentos: ['Nascimento miraculado', 'Sacrifício em Moriá (pelo pai)', 'Casamento com Rebeca', 'Abençoou Jacó e Esaú', 'Escavação de poços'],
    passagensRelevantes: ['Gênesis 21-35', 'Hebreus 11:20'],
    relacionados: ['Abraão', 'Sara', 'Rebeca', 'Jacó', 'Esaú'],
  },
  {
    id: 'jaco',
    nome: 'Jacó',
    nomesAlternativos: ['Israel'],
    testamento: 'AT',
    periodo: 'Patriarcas',
    dataAproximada: 'c. 1800 a.C.',
    papel: 'Patriarca / Antencipador',
    categoria: 'Pentateuco',
    livro: 'Gênesis',
    resumo: 'Filho de Isaque, pai dos 12 tribos de Israel. Teve uma vida de lutas e experiências transformadoras com Deus.',
    caracteristicas: ['Lutador', 'Estrategista', 'Transformado por Deus', 'Pai das 12 tribos'],
    principaisAcontecimentos: ['Luta com o anjo em Peniel', 'Roubo da primogenitura', 'Bênção recebida por engano', 'Luto com o anjo (Peniel)', 'Reunião com Esaú', '12 filhos (os patriarcas das tribos)'],
    passagensRelevantes: ['Gênesis 25-50', 'Oséias 12:3-5', 'Jeremias 30:10-11'],
    relacionados: ['Isaque', 'Esaú', 'José', 'Raquel', 'Lea'],
  },
  {
    id: 'josue',
    nome: 'Josué',
    testamento: 'AT',
    periodo: 'Conquista',
    dataAproximada: 'c. 1400 a.C.',
    papel: 'Líder militar / Sucessor de Moisés',
    categoria: 'Livros Históricos',
    livro: 'Josué',
    resumo: 'Líder que conduziu Israel na conquista de Canaã. Sucessor de Moisés e example de fidelidade a Deus.',
    caracteristicas: ['Corajoso', 'Fiel a Deus', 'Líder militar', 'Exemplo de arrependimento'],
    principaisAcontecimentos: ['Espião em Canaã (com Calebe)', 'Passagem do Jordão', 'Queda de Jericó', 'Conquista de Canaã', 'Discurso de despedida'],
    passagensRelevantes: ['Josué 1-24', 'Números 14:6-9', 'Hebreus 4:8'],
    relacionados: ['Moisés', 'Calebe', 'Raabe', 'Israel'],
  },
  {
    id: 'moises',
    nome: 'Moisés',
    nomesAlternativos: ['Moshé'],
    testamento: 'AT',
    periodo: 'Êxodo',
    dataAproximada: 'c. 1400 a.C.',
    papel: 'Líder / Profeta / Legislador',
    categoria: 'Pentateuco',
    livro: 'Êxodo',
    resumo: 'Maior profeta do Antigo Testamento. Libertou Israel do Egito e recebeu a Lei no Sinai.',
    caracteristicas: ['Humilde (Números 12:3)', 'Fiel', 'Mediador da Aliança', 'Escritor do Pentateuco'],
    principaisAcontecimentos: ['Nascimento e salvamento (cestos de junco)', 'Fuga para Midiã', 'Chamado da sarça ardente', '10 pragas do Egito', 'Passagem do Mar Vermelho', 'Recebimento dos 10 Mandamentos', '44 anos no deserto', 'Morte em Nebo'],
    passagensRelevantes: ['Êxodo-Deuteronômio', 'Hebreus 11:23-29', 'Atos 7:20-44', 'Deuteronômio 34:10-12'],
    relacionados: ['Aarão', 'Miriam', 'Faraó', 'Josué', 'Israel'],
  },
  {
    id: 'aaron',
    nome: 'Aarão',
    testamento: 'AT',
    periodo: 'Êxodo',
    dataAproximada: 'c. 1400 a.C.',
    papel: 'Primeiro Sumo Sacerdote',
    categoria: 'Pentateuco',
    livro: 'Êxodo',
    resumo: 'Irmão de Moisés e primeiro sumo sacerdote de Israel. Participou da construção do bezerro de ouro.',
    caracteristicas: ['Primeiro sumo sacerdote', 'Porta-voz de Moisés', 'Falível'],
    principaisAcontecimentos: ['Porteiro junto a Faraó', 'Nomeação como sacerdote', 'Bezerro de ouro (falha)', 'Ministério sacerdotal', 'Morte em Hor'],
    passagensRelevantes: ['Êxodo 4-40', 'Levítico 8-10', 'Hebreus 5:4'],
    relacionados: ['Moisés', 'Miriam', 'Bezerro de ouro'],
  },
  {
    id: 'deborah',
    nome: 'Débora',
    testamento: 'AT',
    periodo: 'Juizes',
    dataAproximada: 'c. 1100 a.C.',
    papel: 'Profetisa / Juíza',
    categoria: 'Livros Históricos',
    livro: 'Juízes',
    resumo: 'Quarta juíza de Israel e única profetisa que liderou militarmente. Liderou Israel com Baraque.',
    caracteristicas: ['Profetisa', 'Juíza', 'Líder militar', 'Poeta (Cântico de Débora)'],
    principaisAcontecimentos: ['Juíza de Israel', 'Cântico de Débora (Juízes 5)', 'Batalha contra Sísera', 'Vencedora pelo general Baraque'],
    passagensRelevantes: ['Juízes 4-5', 'Hebreus 11:32'],
    relacionados: ['Barake', 'Sísera', 'Jael'],
  },
  {
    id: 'samuel',
    nome: 'Samuel',
    testamento: 'AT',
    periodo: 'Monarquia',
    dataAproximada: 'c. 1050 a.C.',
    papel: 'Profeta / Juiz / Ungidor de reis',
    categoria: 'Livros Históricos',
    livro: '1 Samuel',
    resumo: 'Último juiz de Israel e primeiro grande profeta. Ungiu Saul e Davi como reis.',
    caracteristicas: ['Sagrado desde o nascimento', 'Ouve a voz de Deus', 'Moralista', 'Pai espiritual de Saul e Davi'],
    principaisAcontecimentos: ['Nascimento prometido (Ana)', 'Chamado "Samuel!" no templo', 'Juiz de Israel', 'Ungiu Saul como rei', 'Ungiu Davi como rei', 'Ministério profético contra Saul'],
    passagensRelevantes: ['1 Samuel 1-25', 'Salmos 99:6', 'Hebreus 11:32'],
    relacionados: ['Eli', 'Saul', 'Davi', 'Ana', 'Sansão'],
  },
  {
    id: 'davi',
    nome: 'Davi',
    testamento: 'AT',
    periodo: 'Monarquia',
    dataAproximada: 'c. 1000 a.C.',
    papel: 'Rei / Profeta / Músico',
    categoria: 'Livros Históricos',
    livro: '1 Samuel',
    resumo: 'Maior rei de Israel, poeta, músico e profeta. Ancestral de Jesus Cristo. Homem segundo o coração de Deus.',
    caracteristicas: ['Menino pastor', 'Músico', 'Guerreiro', 'Poeta (Salmos)', 'Pecador arrependido', 'Antencipador de Cristo'],
    principaisAcontecimentos: ['Duelo com Golias', 'Amizade com Jônatas', 'Unção por Samuel', 'Fuga de Saul', 'Adulação por Absalão', 'Salmo 23 (Bom Pastor)', 'Covil da arca', 'Pacto com Deus (2 Samuel 7)'],
    passagensRelevantes: ['1-2 Samuel', '1 Crônicas', 'Salmos (muitos)', 'Mateus 1:6', 'Atos 13:22', 'Hebreus 4:7'],
    relacionados: ['Golias', 'Jônatas', 'Bate-Seba', 'Salomão', 'Abigail', 'Saul'],
  },
  {
    id: 'salomao',
    nome: 'Salomão',
    testamento: 'AT',
    periodo: 'Monarquia',
    dataAproximada: 'c. 970-930 a.C.',
    papel: 'Rei / Sábio / Construtor',
    categoria: 'Livros Históricos',
    livro: '1 Reis',
    resumo: 'Filho de Davi, conhecido pela sabedoria. Construiu o Primeiro Templo em Jerusalém.',
    caracteristicas: ['Sábio', 'Rico', 'Pacífico', 'Cobiçoso na velhice'],
    principaisAcontecimentos: ['Juízo das duas mães (bebé)', 'Construção do Templo', 'Glória de Salomão', 'Livros: Provérbios, Eclesiastes, Cânticos', 'Apostasia no final do reinado'],
    passagensRelevantes: ['1 Reis 1-11', 'Provérbios 1-31', 'Eclesiastes', 'Cânticos', 'Mateus 6:29'],
    relacionados: ['Davi', 'Bate-Seba', 'Reino do Norte/Sul', 'Abdias', 'Rei de Tiro'],
  },
  {
    id: 'elias',
    nome: 'Elias',
    testamento: 'AT',
    periodo: 'Monarquia',
    dataAproximada: 'c. 870 a.C.',
    papel: 'Profeta',
    categoria: 'Profetas Maiores',
    livro: '1 Reis',
    resumo: 'Grande profeta que confrontou os profetas de Baal. Sua vida termina com um arrebatamento miraculoso.',
    caracteristicas: ['Fervoroso', 'Corajoso', 'Homem de oração', 'Peculiar na Transfiguração'],
    principaisAcontecimentos: ['A堂ejo da seca (3 anos)', 'Confronto no Monte Carmelo (Baal)', 'Oração pela chuva', 'Fuga para o Monte Horebe', 'Alimentação por corvos', 'Multiplicação da farinha e azeite (Viúva de Sarepta)', 'Arrebatamento num carro de fogo', 'Transfiguração (com Cristo)'],
    passagensRelevantes: ['1 Reis 17-19, 21', '2 Reis 1-2', 'Malaquias 4:5', 'Mateus 17:3', 'Tiago 5:17'],
    relacionados: ['Eliseu', 'Acabe', 'Jezabel', 'Viúva de Sarepta'],
  },
  {
    id: 'eliseu',
    nome: 'Eliseu',
    testamento: 'AT',
    periodo: 'Monarquia',
    dataAproximada: 'c. 850 a.C.',
    papel: 'Profeta',
    categoria: 'Profetas Menores',
    livro: '2 Reis',
    resumo: 'Sucessor de Elias, realizou mais milagres que qualquer outro profeta. Chamado com manto lançado sobre ele.',
    caracteristicas: ['Milagroso', 'Fiel', 'Gentil', 'Manso'],
    principaisAcontecimentos: ['Sucessor de Elias', 'Manto дух дух дух (duplicação)', 'Cura de Naamã (lepra)', 'Multiplicação do azeite (viúva)', 'Nutrição em apuros (óleo)', 'Axes flutuando (madeira)', 'Resurreição do filho da sunamita'],
    passagensRelevantes: ['2 Reis 2-13', 'Lucas 4:27'],
    relacionados: ['Elias', 'Naamã', 'Geazi'],
  },
  {
    id: 'jeremias',
    nome: 'Jeremias',
    testamento: 'AT',
    periodo: 'Monarquia / Exílio',
    dataAproximada: 'c. 627-586 a.C.',
    papel: 'Profeta',
    categoria: 'Profetas Maiores',
    livro: 'Jeremias',
    resumo: 'O "profeta das lágrimas". Pregou durante o declínio de Judá e destruição de Jerusalém.',
    caracteristicas: ['O "profeta chorão"', 'Perseguido', 'Introverso', 'Messiânico (pacto novo)'],
    principaisAcontecimentos: ['Chamado profético (Jeremias 1)', 'Pregação em Judá', 'Lamentos (Lamentações)', 'Profecia do pacto novo (Jeremias 31)', 'Profecia da destruição de Jerusalém', 'Fica em Judá após o exílio'],
    passagensRelevantes: ['Jeremias 1-52', 'Lamentações', 'Mateus 16:14', 'Hebreus 8:8-13'],
    relacionados: ['Josias', 'Sedekias', 'Ezekiel', 'Daniel'],
  },
  {
    id: 'ezequiel',
    nome: 'Ezequiel',
    testamento: 'AT',
    periodo: 'Exílio',
    dataAproximada: 'c. 593-571 a.C.',
    papel: 'Profeta / Sacerdote',
    categoria: 'Profetas Maiores',
    livro: 'Ezequiel',
    resumo: 'Profeta e sacerdote que profetizou aos exilados em Babilônia. Suas visões incluem a nova terra e o templo restaurado.',
    caracteristicas: ['Sacerdote e profeta', 'Visions dramáticas', 'Messiânico (Rebanho de Deus)', 'Escatológico (volta de Deus)'],
    principaisAcontecimentos: ['Visão da glória de Deus (Ezequiel 1)', 'Visão dos ossos secos (Ezequiel 37)', 'Profeta do exílio', 'Visão do novo templo (Ezequiel 40-48)', 'Profunda destruição profetizada'],
    passagensRelevantes: ['Ezequiel 1-48', 'Daniel 3-12 (tempo de)'],
    relacionados: ['Jeremias', 'Daniel', 'Exilados de Judá'],
  },
  {
    id: 'daniel',
    nome: 'Daniel',
    testamento: 'AT',
    periodo: 'Exílio',
    dataAproximada: 'c. 605-536 a.C.',
    papel: 'Profeta / Governante',
    categoria: 'Profetas Maiores',
    livro: 'Daniel',
    resumo: 'Jovem profeta levado ao exílio em Babilônia. Conhecido pela fidelidade a Deus e pelas visões proféticas.',
    caracteristicas: ['Fiel em toda circunstância', 'Jovem propheta', 'Governante em Babilônia', 'Visions proféticas'],
    principaisAcontecimentos: ['Fossa dos leões', 'Câmara dos fogo ardente', 'Interpretação dos sonhos de Nabucodonosor', 'Visão das 4 feras (Daniel 7)', 'Visão das 70 semanas (Daniel 9)', 'Profecia da estátua e das 4 feras'],
    passagensRelevantes: ['Daniel 1-12', 'Ezequiel 14:14, 20', 'Mateus 24:15', 'Apocalipse 13 (queda)'],
    relacionados: ['Nabucodonosor', 'Ester (tempo de)', 'Esdras (tempo de)'],
  },
  {
    id: 'ester',
    nome: 'Ester',
    testamento: 'AT',
    periodo: 'Pós-Exílio',
    dataAproximada: 'c. 480 a.C.',
    papel: 'Rainha / Salvadora',
    categoria: 'Livros Históricos',
    livro: 'Ester',
    resumo: 'Rainha persa que interveio para salvar seu povo da destruição. Celebrada na festa de Purim.',
    caracteristicas: ['Bela', 'Corajosa', 'Estratégica', 'Fiel ao seu povo'],
    principaisAcontecimentos: ['Torna-se rainha', 'Jejum de 3 dias', 'Descobrimento do complô de Hamã', 'Inversão de sorte (Purim)'],
    passagensRelevantes: ['Ester 1-10', 'Hebreus 11:23'],
    relacionados: ['Mardoqueu', 'Assuero (Xerxes)', 'Hamã'],
  },
  {
    id: 'esdras',
    nome: 'Esdras',
    testamento: 'AT',
    periodo: 'Pós-Exílio',
    dataAproximada: 'c. 458 a.C.',
    papel: 'Sacerdote / Escriba',
    categoria: 'Livros Históricos',
    livro: 'Esdras',
    resumo: 'Sacerdote e escriba que liderou o retorno do exílio babilônico e a reforma religiosa em Judá.',
    caracteristicas: ['Sacerdote', 'Escriba', 'Reformador', 'Expert na Lei'],
    principaisAcontecimentos: ['Retorno do exílio (458 a.C.)', 'Reconstrução do Templo', 'Reforma religiosa', 'Ensino da Lei'],
    passagensRelevantes: ['Esdras 7-10', 'Neemias 8'],
    relacionados: ['Artaxerxes', 'Neemias', 'Zorobabel'],
  },
  {
    id: 'neemias',
    nome: 'Neemias',
    testamento: 'AT',
    periodo: 'Pós-Exílio',
    dataAproximada: 'c. 445 a.C.',
    papel: 'Governador / Reformador',
    categoria: 'Livros Históricos',
    livro: 'Neemias',
    resumo: 'Copeiro do rei da Pérsia que liderou a reconstrução das muralhas de Jerusalém.',
    caracteristicas: ['Orante', 'Líder prático', 'Corajoso', 'Reformador social'],
    principaisAcontecimentos: ['Reconstrução das muralhas de Jerusalém', 'Oração pela nação (Neemias 1)', 'Reforma social (liberdade para devedores)', 'Renovação da aliança'],
    passagensRelevantes: ['Neemias 1-13', 'Esdras 4-7 (tempo de)'],
    relacionados: ['Artaxerxes', 'Esdras', 'Esdras 4:7 (tempo de)'],
  },
  // ─── NOVO TESTAMENTO ────────────────────────────────────────────────────────
  {
    id: 'jesus',
    nome: 'Jesus Cristo',
    nomesAlternativos: ['Jesus de Nazaré', 'Cristo', 'Emmanuel', 'Filho do Homem', 'Cordeiro de Deus'],
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 4 a.C. - 30 d.C.',
    papel: 'Filho de Deus / Salvador / Messias',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'O Filho de Deus encarnado, Salvador do mundo. Viveu, morreu e ressuscitou para redimir a humanidade.',
    caracteristicas: ['Filho de Deus', 'Samaritano', 'Profeta', 'Sumo Sacerdote', 'Rei', 'Mestre (Rabbi)', 'Milagroso', 'Humilde', 'Santo'],
    principaisAcontecimentos: ['Nascimento em Belém', 'Batismo por João', 'Tentação no deserto', 'Sermão da Montanha', 'Milagres (todos)', 'Transfiguração', 'Entrada messiânica em Jerusalém', 'Última Ceia', 'Prisão, morte e sepultamento', 'Ressurreição', 'Ascensão', 'Promessa do Espírito Santo'],
    passagensRelevantes: ['Mateus-Marcos-Lucas-João', 'Romanos 3:23-26', '1 Coríntios 15:1-8', 'Filipenses 2:5-11', 'Hebreus 4:14-16', 'João 3:16', 'João 14:6'],
    relacionados: ['Maria', 'José', 'João Batista', 'Apóstolos', 'Paulo', 'Maria Madalena'],
  },
  {
    id: 'maria-mae',
    nome: 'Maria (Mãe de Jesus)',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 20 a.C. - 45 d.C.',
    papel: 'Mãe de Jesus / Santíssima',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'Mãe virginal de Jesus Cristo, escolhida por Deus para ser a mãe do Salvador.',
    caracteristicas: ['Virgem', 'Humilde', 'Fiel', 'Mãe de Jesus'],
    principaisAcontecimentos: ['Anunciação (Lc 1)', 'Visitação a Isabel', 'Nascimento de Jesus em Belém', 'Fuga para o Egito', 'Perdido no Templo (aos 12)', 'Presente nas bodas de Caná', 'Ao pé da cruz'],
    passagensRelevantes: ['Mateus 1-2', 'Lucas 1-2', 'João 2', 'João 19:25-27'],
    relacionados: ['Jesus', 'José', 'Elisabete', 'João Batista (primo)'],
  },
  {
    id: 'joao-batista',
    nome: 'João Batista',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 6 a.C. - 30 d.C.',
    papel: 'Precursor de Cristo / Batista',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'O último e maior profeta do Antigo Testamento, que preparou o caminho para Jesus Cristo.',
    caracteristicas: ['Precursor do Messias', 'Ermitão', 'Povo austero', 'Pregador do arrependimento'],
    principaisAcontecimentos: ['Nascimento anunciado (Lc 1)', 'Vida no deserto', 'Pregação: "Arrependam-se"', 'Batismo de Jesus', 'Ministério na Judéia', 'Prisão por Herodes', 'Degolação', 'Jesus: "o maior nascido de mulher"'],
    passagensRelevantes: ['Mateus 3', 'Marcos 1', 'Lucas 1-3', 'João 1:6-37', 'Mateus 11:11', 'Mateus 14:1-12'],
    relacionados: ['Jesus', 'Herodes Antipas', 'Isabel', 'Zacarias (pai)'],
  },
  {
    id: 'pedro',
    nome: 'Pedro (Simão Pedro)',
    nomesAlternativos: ['Simão Pedro', 'Cefas'],
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-67 d.C.',
    papel: 'Apóstolo / Líder dos Apóstolos',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'Apóstolo líder, primeiro a confessar Jesus como o Cristo. Pastor da Igreja primitiva.',
    caracteristicas: ['Impulsivo', 'Corajoso (por vezes)', 'Líder', 'Pastoral', 'Negou Cristo 3x', 'Arrependido'],
    principaisAcontecimentos: ['Chamado como discípulo', 'Confissão messiânica (Mt 16)', 'Transfiguração', 'Lavagem dos pés', 'Negação de Jesus (3x)', 'Ressurreição (aparição)', 'Pentecoste (3000 convertidos)', 'Martírio (pendurado de cabeça para baixo)'],
    passagensRelevantes: ['Mateus 10:2', 'Mateus 14:22-33', 'Mateus 16:13-20', 'Mateus 26:69-75', 'João 21', 'Atos 1-12', '1-2 Pedro'],
    relacionados: ['Jesus', 'André (irmão)', 'Paulo (conflito inicial)', 'João'],
  },
  {
    id: 'paulo',
    nome: 'Paulo (Saulo de Tarso)',
    nomesAlternativos: ['Saulo de Tarso', 'Apóstolo Paulo'],
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 5-67 d.C.',
    papel: 'Apóstolo / Missionário / Teólogo',
    categoria: 'Cartas Paulinas',
    livro: 'Atos',
    resumo: 'Maior missionário da história cristã, autor de grande parte do Novo Testamento.',
    caracteristicas: ['Fariseu', 'Cidadão romano', 'Teólogo', 'Missionário', 'Apóstolo aos gentios', 'Sofredor'],
    principaisAcontecimentos: ['Perseguidor dos cristãos (Saulo)', 'Conversão no caminho de Damasco', 'Chamado como apóstolo', 'Viagens missionárias (3)', 'Prisão em Roma', 'Martírio em Roma', '13 epístolas do NT'],
    passagensRelevantes: ['Atos 7-28', 'Romanos', '1-2 Coríntios', 'Gálatas', 'Efésios', 'Filipenses', 'Colossenses', '1-2 Tessalonicenses', '1-2 Timóteo', 'Tito', 'Filemom', 'Hebreus (atrib.)'],
    relacionados: ['Barnabé', 'Timóteo', 'Silas', 'Barnabé', 'Bernice', 'Félix', 'Festus', 'Agrippa'],
  },
  {
    id: 'joao',
    nome: 'João',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 6 - 100 d.C.',
    papel: 'Apóstolo / Evangelista / Profeta',
    categoria: 'Evangelhos',
    livro: 'João',
    resumo: 'O apóstolo do amor, autor do quarto Evangelho, Apocalipse e três epístolas.',
    caracteristicas: ['O "discípulo amado"', 'Amigo de Pedro', 'Apocalíptico', 'Teólogo do amor'],
    principaisAcontecimentos: ['Discípulo de Jesus', 'Presente na transfiguração', 'Ao pé da cruz (cuidou de Maria)', 'Ressurreição (túmulo vazio)', 'Rejeição em Samaria', 'Exílio em Patmos', 'Autor de João, 1-3 João e Apocalipse'],
    passagensRelevantes: ['João 1-21', '1-3 João', 'Apocalipse', 'Mateus 17:1-9 (transfiguração)', 'João 13:23', 'João 19:26'],
    relacionados: ['Jesus', 'Pedro', 'Tiago (irmão)', 'Maria Madalena'],
  },
  {
    id: 'maria-madalena',
    nome: 'Maria Madalena',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 14-49 d.C.',
    papel: 'Discípula / Testemunha da ressurreição',
    categoria: 'Evangelhos',
    livro: 'Lucas',
    resumo: 'Mulher de quem Jesus expulsou sete demônios. Primeira testemunha da ressurreição.',
    caracteristicas: ['Libertada por Jesus', 'Fiel ao Calvário', 'Primeira testemunha da ressurreição', 'Doadora'],
    principaisAcontecimentos: ['7 demônios expulsos por Jesus', 'Acompanhava Jesus em suas viagens', 'Estava na crucificação', 'Primeira no túmulo vazio', 'Anunciou a ressurreição aos apóstolos'],
    passagensRelevantes: ['Lucas 8:2', 'Mateus 27:56, 61', 'Marcos 15:40-47', 'João 19:25', 'João 20:1-18'],
    relacionados: ['Jesus', 'Pedro', 'Joana', 'Susana'],
  },
  {
    id: 'estevao',
    nome: 'Estêvão',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 34 d.C.',
    papel: 'Diácono / Primeiro mártir',
    categoria: 'Atos dos Apóstolos',
    livro: 'Atos',
    resumo: 'Primeiro mártir cristão, morto por apedrejamento. Sua defesa diante do Sinédrio é a mais longa fala registrada em Atos.',
    caracteristicas: ['Cheio do Espírito', 'Poderoso em obras', 'Primeiro mártir', 'Perdoou seus assassinos'],
    principaisAcontecimentos: ['Escolhido como diácono (Atos 6)', 'Ministério social (mesas)', 'Discurso no Sinédrio (Atos 7)', 'Apedrejado até a morte', 'Rogou por seus assassinos'],
    passagensRelevantes: ['Atos 6-7', 'Atos 8:2 (luto por ele)', 'Hebreus 11:32-38'],
    relacionados: ['Saulo de Tarso (presente no apedrejamento)', 'Apóstolos'],
  },
  {
    id: 'estevao',
    nome: 'Lázaro',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-50 d.C.',
    papel: 'Amigo de Jesus / Ressuscitado',
    categoria: 'Evangelhos',
    livro: 'João',
    resumo: 'Amigo de Jesus que morreu e foi ressuscitado por Ele, demonstrando Seu poder sobre a morte.',
    caracteristicas: ['Amigo de Jesus', 'Irmão de Marta e Maria', 'Ressuscitado por Jesus'],
    principaisAcontecimentos: ['Adoeceu e morreu', 'Jesus chorou à sua sepultura', 'Ressuscitado após 4 dias (João 11)', 'Presente no jantar em Betânia (João 12)'],
    passagensRelevantes: ['João 11:1-44', 'João 12:1-11'],
    relacionados: ['Jesus', 'Marta', 'Maria (irmã de Lázaro)'],
  },
  {
    id: 'timoteo',
    nome: 'Timóteo',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 17-97 d.C.',
    papel: 'Discípulo / Missionário de Paulo',
    categoria: 'Cartas Paulinas',
    livro: 'Atos',
    resumo: 'Jovem convertido por Paulo, seu filho na fé. Companheiro de viagens missionárias.',
    caracteristicas: ['Jovem', 'Timido', 'Fiel', 'Filho na fé de Paulo'],
    principaisAcontecimentos: ['Conversão através de Paulo', 'Companheiro de viagens', 'Liderou igreja em Éfeso (1 Timóteo)', 'Liderou igreja em Filipos', 'Autor de 1-2 Timóteo', 'Tito (colega)'],
    passagensRelevantes: ['Atos 16:1-3', '1-2 Timóteo', 'Romanos 16:21', 'Filipenses 1:1', 'Colossenses 1:1', '1 Tessalonicenses 1:1', '2 Tessalonicenses 1:1', 'Filemom 1:1', 'Hebreus 13:23'],
    relacionados: ['Paulo', 'Eunice (mãe)', 'Lois (avó)', 'Tito'],
  },
  {
    id: 'barnabe',
    nome: 'Barnabé',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-61 d.C.',
    papel: 'Apóstolo / Missionário',
    categoria: 'Atos dos Apóstolos',
    livro: 'Atos',
    resumo: 'Companheiro de Paulo nas primeiras viagens missionárias. Conhecido por encorajar novos crentes.',
    caracteristicas: ['Encorajador', 'Generoso', 'Sacerdote levita', 'Desacordo com Paulo (separação)'],
    principaisAcontecimentos: ['Vendeu terra e doou ao grupo', 'Apresentou Paulo aos apóstolos', 'Primeira viagem com Paulo (Chipre)', 'Separou-se de Paulo (segunda viagem)', 'Ministrou em Antioquia'],
    passagensRelevantes: ['Atos 4:36-37', 'Atos 9:26-30', 'Atos 11:19-26', 'Atos 13-15'],
    relacionados: ['Paulo', 'Marcos (sobrinho)', 'João Marcos'],
  },
  {
    id: 'filipe',
    nome: 'Filipe (Diácono)',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-80 d.C.',
    papel: 'Diácono / Evangelista',
    categoria: 'Atos dos Apóstolos',
    livro: 'Atos',
    resumo: 'Um dos sete primeiros diáconos, conhecido por suas obras e por levar o Evangelho a Samaria e ao eunuco etíope.',
    caracteristicas: ['Diácono', 'Evangelista', 'Homem cheio do Espírito', '5 filhas prophetisas'],
    principaisAcontecimentos: ['Escolhido como diácono (Atos 6)', 'Pregação em Samaria', 'Batismo do eunuco etíope (carro de Filipe)', 'Fuga de Gaza', 'Casamento e 5 filhas prophetisas'],
    passagensRelevantes: ['Atos 6:1-6', 'Atos 8:4-40', 'Atos 21:8-9'],
    relacionados: ['Paulo (batizado por Filipe)', 'Etíope (eunuco)', 'Pedro', 'João'],
  },
  {
    id: 'nicodemos',
    nome: 'Nicodemos',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-70 d.C.',
    papel: 'Fariseu / Mestre em Israel',
    categoria: 'Evangelhos',
    livro: 'João',
    resumo: 'Fariseu e mestre em Israel que visitou Jesus à noite. Defensores de Jesus no Sinédrio.',
    caracteristicas: ['Fariseu', 'Mestre em Israel', 'Notável entre os Judeus', 'Nocturno (visita à noite)'],
    principaisAcontecimentos: ['Visita nocturna a Jesus (João 3)', 'Conversa sobre o novo nascimento', 'Jesus: "Deus amou o mundo"', 'Defendeu Jesus no Sinédrio', 'Presente na unção de Jesus (João 12)', 'Jo 3:1-21 — novo nascimento, Deus amou o mundo'],
    passagensRelevantes: ['João 3:1-21', 'João 7:45-52', 'João 19:38-42'],
    relacionados: ['Jesus', 'Fariseus', 'Jose de Arimateia'],
  },
  {
    id: 'jose-arimateia',
    nome: 'José de Arimateia',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: 'c. 1-70 d.C.',
    papel: 'Membro do Sinédrio / Disípulo secreto',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'Membro do Sinédrio que pediu a Pilatos o corpo de Jesus e o sepultou em seu próprio túmulo.',
    caracteristicas: ['Membro do Sinédrio', 'Disípulo secreto', 'Rico', 'Piedoso'],
    principaisAcontecimentos: ['Era discípulo de Jesus (secreto)', 'Pediu a Pilatos o corpo de Jesus', 'Sepultou Jesus no seu próprio túmulo novo', 'Membro do Sinédrio (mas não consentiu na crucificação)'],
    passagensRelevantes: ['Mateus 27:57-60', 'Marcos 15:42-46', 'Lucas 23:50-56', 'João 19:38-42'],
    relacionados: ['Jesus', 'Nicodemos', 'Pilatos'],
  },
  {
    id: 'herodes-antipas',
    nome: 'Herodes Antipas',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: '20 a.C. - 39 d.C.',
    papel: 'Tetrarca da Galiléia',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'Tetrarca que prendeu e degolou João Batista, e zombou de Jesus durante o julgamento.',
    caracteristicas: ['Político', 'Adúltero', 'Covarde', 'Supersticioso'],
    principaisAcontecimentos: ['Casou-se com Herodias (mulher do irmão)', 'Prendeu João Batista', 'Degolou João Batista (aniversário)', 'Julga Jesus (zombou dele)', 'Jesus: "raposa" (Lucas 13:31)'],
    passagensRelevantes: ['Mateus 14:1-12', 'Marcos 6:14-29', 'Lucas 3:19-20', 'Lucas 13:31-32', 'Lucas 23:6-12'],
    relacionados: ['João Batista', 'Herodias', 'Salomé', 'Jesus', 'Pilatos'],
  },
  {
    id: 'pilatos',
    nome: 'Pôncio Pilatos',
    testamento: 'NT',
    periodo: 'Nova Aliança',
    dataAproximada: '26-36 d.C.',
    papel: 'Prefeito romano da Judéia',
    categoria: 'Evangelhos',
    livro: 'Mateus',
    resumo: 'Governador romano que julgou Jesus e, apesar de não encontrar culpa, permitiu sua crucificação.',
    caracteristicas: ['Prefeito romano', 'Covarde (lavou as mãos)', 'Interessado na verdade', 'Cobiçoso'],
    principaisAcontecimentos: ['Jesus traído', 'Interrogou Jesus', '"Que é verdade?" (João 18:38)', '"Não encontro culpa neste homem"', 'Lavou as mãos', 'Entregou Jesus para ser crucificado', 'Fugiu da responsabilidade'],
    passagensRelevantes: ['Mateus 27:1-26', 'Marcos 15:1-15', 'Lucas 23:1-25', 'João 18:28-40', '1 Timóteo 6:13'],
    relacionados: ['Jesus', 'Herodes Antipas', 'Caifás', 'Sinédrio'],
  },
];

/**
 * Busca personagens por nome, livro, período ou papel.
 * Busca case-insensitive.
 */
export function buscarPersonagens(termo: string): PersonagemBiblico[] {
  if (!termo.trim()) return [];
  const q = termo.toLowerCase().trim();

  return PERSONAGENS.filter((p) => {
    if (p.nome.toLowerCase().includes(q)) return true;
    if (p.nomesAlternativos?.some((n) => n.toLowerCase().includes(q))) return true;
    if (p.livro?.toLowerCase().includes(q)) return true;
    if (p.periodo?.toLowerCase().includes(q)) return true;
    if (p.papel.toLowerCase().includes(q)) return true;
    if (p.categoria.toLowerCase().includes(q)) return true;
    if (p.testamento.toLowerCase().includes(q)) return true;
    if (p.resumo.toLowerCase().includes(q)) return true;
    if (p.relacionados?.some((r) => r.toLowerCase().includes(q))) return true;
    if (p.principaisAcontecimentos.some((a) => a.toLowerCase().includes(q))) return true;
    return false;
  });
}

export const PERIODOS = [...new Set(PERSONAGENS.map((p) => p.periodo).filter(Boolean))] as string[];
export const TESTAMENTOS = ['AT', 'NT'] as const;
export const CATEGORIAS = [...new Set(PERSONAGENS.map((p) => p.categoria))].sort();
