const fs = require('fs');
const path = 'src/lib/ai/openai.ts';
let s = fs.readFileSync(path, 'utf8');

const start = s.indexOf('  async enviar(req: AIRequest)');
const end = s.indexOf('  estimarTokens(texto: string)');
if (start === -1 || end === -1) {
  console.error('Marcadores nao encontrados');
  process.exit(1);
}

const before = s.substring(0, start);
const after = s.substring(end);

const newMethod = [
  '  async enviar(req: AIRequest): Promise<AIResponse> {',
  '    const sb = supabase();',
  '    if (!sb) throw new AIError("Supabase nao disponivel", "rede", "openai");',
  '',
  '    const inicioMs = Date.now();',
  '    const querStream = req.stream === true && typeof req.onChunk === "function";',
  '',
  '    // Pega JWT da sessao atual (Edge Function exige Authorization)',
  '    const { data: { session } } = await sb.auth.getSession();',
  '    const jwt = session?.access_token;',
  '    if (!jwt) throw new AIError("Sessao expirada. Faca login novamente.", "sem-chave", "openai");',
  '',
  '    const supabaseUrl = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? "";',
  '    const anonKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ?? "";',
  '    if (!supabaseUrl || !anonKey) throw new AIError("Configuracao Supabase ausente", "rede", "openai");',
  '',
  '    const body = JSON.stringify({',
  '      messages: req.messages.map((m) => ({ role: m.role, content: m.content })),',
  '      systemAppend: req.systemAppend ?? "",',
  '      maxTokens: req.maxTokens ?? 2500,',
  '      temperature: req.temperature ?? 0.7,',
  '      stream: querStream,',
  '      agente_id: (req as { agenteId?: string }).agenteId ?? null,',
  '    });',
  '',
  '    const fetchOpts: RequestInit = {',
  '      method: "POST",',
  '      headers: {',
  '        "Content-Type": "application/json",',
  '        "Authorization": `Bearer ${jwt}`,',
  '        "apikey": anonKey,',
  '      },',
  '      body,',
  '      signal: req.signal,',
  '    };',
  '',
  '    try {',
  '      const res = await fetch(`${supabaseUrl}/functions/v1/ai-chat`, fetchOpts);',
  '',
  '      if (!res.ok) {',
  '        const errorBody = await res.text().catch(() => "");',
  '        let parsed: { error?: string; message?: string } = {};',
  '        try { parsed = JSON.parse(errorBody); } catch { parsed = { message: errorBody }; }',
  '        const codigo = parsed.error ?? "";',
  '        const mensagem = parsed.message ?? errorBody;',
  '',
  '        if (codigo === "invalid_token" || res.status === 401) throw new AIError("Sessao expirada.", "sem-chave", "openai");',
  '        if (codigo === "no_api_key") throw new AIError("IA nao configurada. Cadastre chave em /admin/api-keys.", "sem-chave", "openai");',
  '        if (codigo === "limit_reached" || res.status === 429) throw new AIError("Limite mensal de IA atingido.", "tokens-excedidos", "openai");',
  '        throw new AIError("Erro no servidor: " + mensagem.slice(0, 300), "desconhecido", "openai");',
  '      }',
  '',
  '      // ---- STREAMING (SSE) ----',
  '      if (querStream) {',
  '        const reader = res.body?.getReader();',
  '        const decoder = new TextDecoder();',
  '        if (!reader) throw new AIError("Stream indisponivel", "resposta-invalida", "openai");',
  '',
  '        let buffer = "";',
  '        let accumulated = "";',
  '        let provider = "openai";',
  '        let model = "gpt-4o-mini";',
  '        let tokensInput = 0;',
  '        let tokensOutput = 0;',
  '        let custoUSD = 0;',
  '        let erroMsg: string | null = null;',
  '',
  '        while (true) {',
  '          const { done, value } = await reader.read();',
  '          if (done) break;',
  '          buffer += decoder.decode(value, { stream: true });',
  '          const events = buffer.split("\\n\\n");',
  '          buffer = events.pop() ?? "";',
  '          for (const evt of events) {',
  '            const data = evt.replace(/^data:\\s*/, "").trim();',
  '            if (!data || data === "[DONE]") continue;',
  '            try {',
  '              const parsed = JSON.parse(data) as {',
  '                content?: string; done?: boolean; error?: string; message?: string;',
  '                provider?: string; model?: string; tokensInput?: number;',
  '                tokensOutput?: number; custoUSD?: number;',
  '              };',
  '              if (parsed.error) { erroMsg = parsed.message ?? parsed.error; break; }',
  '              if (parsed.content) {',
  '                accumulated += parsed.content;',
  '                req.onChunk?.(parsed.content);',
  '              }',
  '              if (parsed.done) {',
  '                provider = parsed.provider ?? provider;',
  '                model = parsed.model ?? model;',
  '                tokensInput = parsed.tokensInput ?? 0;',
  '                tokensOutput = parsed.tokensOutput ?? 0;',
  '                custoUSD = parsed.custoUSD ?? 0;',
  '              }',
  '            } catch { /* skip */ }',
  '          }',
  '        }',
  '',
  '        if (erroMsg) {',
  '          if (erroMsg.includes("no_api_key")) throw new AIError("IA nao configurada.", "sem-chave", "openai");',
  '          if (erroMsg.includes("limit_reached")) throw new AIError("Limite atingido.", "tokens-excedidos", "openai");',
  '          throw new AIError(erroMsg.slice(0, 300), "desconhecido", "openai");',
  '        }',
  '',
  '        return {',
  '          content: accumulated,',
  '          tokensTotal: tokensInput + tokensOutput,',
  '          tokensInput, tokensOutput, model, provider, custoUSD,',
  '          fimEm: Date.now(),',
  '          duracaoMs: Date.now() - inicioMs,',
  '        };',
  '      }',
  '',
  '      // ---- NON-STREAMING ----',
  '      const result = await res.json() as {',
  '        content: string; provider: string; model: string;',
  '        tokensInput: number; tokensOutput: number; tokensTotal: number;',
  '        custoUSD: number; duracaoMs: number;',
  '      };',
  '',
  '      if (!result?.content) throw new AIError("Resposta vazia do servidor", "resposta-invalida", "openai");',
  '',
  '      return {',
  '        content: result.content,',
  '        tokensTotal: result.tokensTotal ?? result.tokensInput + result.tokensOutput,',
  '        tokensInput: result.tokensInput ?? 0,',
  '        tokensOutput: result.tokensOutput ?? 0,',
  '        model: result.model ?? "gpt-4o-mini",',
  '        provider: result.provider ?? "openai",',
  '        custoUSD: result.custoUSD ?? 0,',
  '        fimEm: Date.now(),',
  '        duracaoMs: result.duracaoMs ?? (Date.now() - inicioMs),',
  '      };',
  '    } catch (e) {',
  '      if (e instanceof AIError) throw e;',
  '      const err = e as Error & { name?: string };',
  '      if (err.name === "AbortError") throw new AIError("Cancelado", "cancelado", "openai");',
  '      throw new AIError((e as Error).message ?? "Erro desconhecido", "rede", "openai");',
  '    }',
  '  }',
  '',
  '',
].join('\n');

fs.writeFileSync(path, before + newMethod + after);
console.log('OK -', path, '- new size:', (before + newMethod + after).length, 'bytes');